version: '3'
services:
  app:
    image: ruby:2.7.2-alpine
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

